import numpy as np 

class BigM:
       
    def runBigM(formattedInput: np.ndarray) -> np.ndarray:
        """
        This function solves linear optimisation problems with the Big M method and returns each iteration
        in a seperate matrix.
        Arguments:
            formattedInput: A description matrix generated by BigM.formatUserInput().
        Returns:
            A list of matrices that corresponds to simplex iterations (+ the Big M initial phase of course)
        """
        
        fake_data = arr = np.array([[1, 2.5, 3.2], [0.4, 5, 6]])
        print(fake_data)
        print(type(fake_data))